filtgenmaster.mainMenu.ButtonText: 'Events buchen'
filtgenmaster.mainMenu.ButtonLink: 'https://masterarbeit.ddev.site/events'
filtgenmaster.eventPageBack: 'https://masterarbeit.ddev.site/events'
filtgenmaster.eventPageForward: 'https://masterarbeit.ddev.site/kontakt'
filtgenmaster.datenschutz.Page: 'https://masterarbeit.ddev.site/datenschutz'
filtgenmaster.impressum.Page: 'https://masterarbeit.ddev.site/impressum'
