name: ffiltgen/filtgenmaster
label: Filtgen Master

dependencies: 
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - typo3/seo-sitemap
  - typo3/indexed-search
  - typo3/form
  - typo3/felogin
  