categories:
  filtgenmaster:
    label: "Filtgen site settings"
  mainNavigation:
    parent: filtgenmaster
    label: "Main navigation settings"
  footernavigation:
    parent: filtgenmaster
    label: "Footer navigation settings"
  
settings:
  filtgenmaster.mainMenu.ButtonText:
    category: mainNavigation
    label: "Main Menu Button Text"
    type: string
    default: ""
  filtgenmaster.mainMenu.ButtonLink:
    category: mainNavigation
    label: "Main Menu Button Link"
    type: string
    default: ""
  filtgenmaster.impressum.Page:
    category: footernavigation
    label: "Link des Impressum buttons"
    type: string
    default: ""
  filtgenmaster.datenschutz.Page:
    category: footernavigation
    label: "Link des Datenschutz buttons"
    type: string
    default: ""
  
  