name: filtgen/event-teaser
typeName: filtgen_eventteaser
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: bttn_link_1
    type: Link
    label: Button 1 Link
    allowedTypes:
      - page
      - url
  - identifier: events
    type: Collection
    labellfield: title
    appearance:
      collapseAll: true
      levelLinksPosition: both
    fields:
      - identifier: title
        type: Text
        label: Titel des Events
      - identifier: image
        label: Teaser Bild des Events
        type: File
        extendedPalette: false
        allowed: common-image-types
      - identifier: link
        type: Link
        label: Link zum Event
        allowedTypes:
          - page
          - url
      - identifier: event_bage
        label: Bage im Teaserbild
        type: Text
      - identifier: event_price
        type: Text
        label: Preis des Events
      - identifier: event_place
        type: Text
        label: Ort des Events
      - identifier: event_small_description
        type: Text
        label: Kurze Beschreibung des Events
      - identifier: event_date
        type: DateTime
        label: Datum des Events
        format: datetime
        dbType: datetime
      - identifier: event_street_location
        type: Text
        label: Hausnummer und Straße des Events
      - identifier: event_ocupation
        type: Text
        label: Belegung des Events
