name: filtgen/about-section
typeName: filtgen_aboutsection
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: bttn_link_1
    type: Link
    label: Button 1 Link
    allowedTypes:
      - page
      - url
  - identifier: image
    label: Teaser Bild des Events
    type: File
    extendedPalette: false
