name: filtgen/about-section-big
typeName: filtgen_aboutsectionbig
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
  - identifier: image
    label: Teaser Bild des Events
    type: File
    extendedPalette: false
