filtgenmaster.mainMenu.ButtonText: 'Events buchen'
filtgenmaster.impressum.Page: 'https://masterarbeit2.ddev.site/impressum'
filtgenmaster.datenschutz.Page: 'https://masterarbeit2.ddev.site/datenschutz'
filtgenmaster.mainMenu.ButtonLink: 'https://masterarbeit2.ddev.site/events'
