name: filtgen/usp-list
typeName: filtgen_usplist
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: bttn_link_1
    type: Link
    label: Button 1 Link
    allowedTypes:
      - page
      - url
